### PR TITLE
feat: add helm chart

### PR DESCRIPTION
**Pull request by david972**
issue #615

### CODE REVIEW

**Comment by david972** [comment]
The chart working well

There is couple of thing that need to do
- I did not find the docker image tag with semver
- need to add some pre-check for the config

**Comment by levkk** [comment]
I have no way to validate that this is correct, but I'm happy to merge it to give it a try. Thanks for the contribution!

**Comment by alexelent-carta** [comment]
what would the `helm repo add` command be to use this chart?

**Comment by code-sauce** [comment]
@david972 @alexelent-carta do we now know how to add this repo to helm?

what's the exact command? Locally, it complains the repository doesn't have `index.yaml`

**Comment by david972** [comment]
hi
for now we'll need to do it locally as the publishing failed
The log is available anymore i cannot investigate
I'll do it later

**Pull request merged**
